# Generated by Django 4.1.6 on 2023-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorinbox',
            name='isseen',
            field=models.BooleanField(default=False),
        ),
    ]
