# Generated by Django 4.1.6 on 2023-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_approval',
            name='is_approval',
            field=models.CharField(blank=True, choices=[('Pandding', 'Pandding'), ('Seleccted', 'Seleccted'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
