# Generated by Django 4.1.6 on 2023-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_project_approval_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_approval',
            name='is_approval',
            field=models.CharField(blank=True, choices=[('Pandding', 'Pandding'), ('Select', 'Select'), ('complete', 'complete'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
