# Generated by Django 4.1.6 on 2023-02-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_project_approval_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_approval',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_approval', to='brands.project'),
        ),
    ]
