# Generated by Django 4.1.6 on 2023-02-11 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_project_approval_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
