# Generated by Django 4.1.6 on 2023-02-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_verified', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_visit', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('country_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.CharField(max_length=400)),
                ('youtube_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('type_of_youtube', models.CharField(max_length=250)),
                ('youtube_subscriber', models.IntegerField(blank=True, default=0, null=True)),
                ('instagram_followers', models.IntegerField(blank=True, default=0, null=True)),
                ('low_Budget', models.IntegerField(blank=True, default=0, null=True)),
                ('high_Budget', models.IntegerField(blank=True, default=0, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_profile_link', models.URLField(max_length=150)),
                ('company_official_email', models.EmailField(max_length=250)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
