# Generated by Django 4.1.6 on 2023-02-11 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='profile_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='creator_profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='creator_profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='youtube_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
