# Generated by Django 4.1.6 on 2023-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_brand_profile_img_creator_instagram_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='profile_img',
            field=models.ImageField(upload_to='brands_profile'),
        ),
    ]
